### ISSUE TITLE
缺少ssl证书

### ISSUE THREAD

**Issue by howrain** [kcn3388/fgogacha#1]
https://github.com/kcn3388/fgogacha/blob/85ba284d871a84d95740a56ae11f9d06f02512b9/download.py#L9
https://github.com/kcn3388/fgogacha/blob/85ba284d871a84d95740a56ae11f9d06f02512b9/getGachaPools.py#L18
试了下发现要ssl证书，我自己是把ssl验证关了，也能正常用

**Comment by kcn3388** [comment]
因为之前遇到过因为证书问题mooncell报403，等下的commit会修

**Comment by kcn3388** [comment]
fixed in [f5bd6ee](https://github.com/kcn3388/fgogacha/commit/f5bd6eef1320f64a28821bb53c86035188053874), please check readme for new feature
已修复[f5bd6ee](https://github.com/kcn3388/fgogacha/commit/f5bd6eef1320f64a28821bb53c86035188053874)，请查看readme以了解新特性
