### ISSUE TITLE
fgogacha安装问题

### ISSUE THREAD

**Issue by parishkill** [kcn3388/fgogacha#3]
尊敬的作者您好：
我安装您的fgo抽卡插件时，出现了以下报错
![image](https://user-images.githubusercontent.com/106006103/187339097-70a7d00a-5211-4683-a8c7-ea77f46ff62e.png)
想问一下是什么插件没装，或是什么指令没有执行吗？

**Comment by kcn3388** [comment]
fix in 9ceb520

**Comment by parishkill** [comment]
尊敬的作者，您好：
![image](https://user-images.githubusercontent.com/106006103/187344213-7bb0ec67-a0a2-4a38-9fe0-8aac349b41fc.png)
更新版本后，可以正常安装了，fgo数据初始化，获取fgo卡池，fgo数据下载都没问题，但是指令fgo十连后又有了新的报错了
![image](https://user-images.githubusercontent.com/106006103/187344437-1bf38231-9a14-43c0-bcfb-e145bf590db9.png)

**Comment by kcn3388** [comment]
fix in a1d76a9
新bug请单开issue，方便归档

**Comment by parishkill** [comment]
好的，感谢指导~
