### ISSUE TITLE
获取新闻报错、指令相应较慢

### ISSUE THREAD

**Issue by TanezakiAtsum1** [kcn3388/fgogacha#4]
第一个问题提示data下没news的json
第二个问题 群里输入fgo十连 要等待5秒以上才会有结果 百连大概率非酋 感觉不太合理

**Comment by kcn3388** [comment]
1. 请提供log
2. 生成图片速度取决于服务器性能

**Comment by kcn3388** [comment]
fix in [5e2571b](https://github.com/kcn3388/fgogacha/commit/5e2571b34fe85f69fabe6f7d1472e04388993d71)
